create table if not exists public.hbg3_dew_status (
  id bigint generated by default as identity primary key,
  station text not null default 'eliot',
  captured_at timestamptz not null default now(),
  connected boolean not null default false,
  raw_data jsonb not null default '{}'::jsonb
);

create index if not exists hbg3_dew_status_station_time_idx
  on public.hbg3_dew_status (station, captured_at desc);

alter table public.hbg3_dew_status enable row level security;

drop policy if exists "Authenticated crew can read HBG3 telemetry"
  on public.hbg3_dew_status;

create policy "Authenticated crew can read HBG3 telemetry"
  on public.hbg3_dew_status
  for select
  to authenticated
  using (true);

-- The local bridge uses the service-role key, which bypasses RLS for inserts.
-- Never place that service-role key in the React/Vite website environment.
